apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myfailingpod
  name: myfailingpod
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    command: ["doesnt-exist"]
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
