apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mymulticontainerpod
  name: mymulticontainerpod
spec:
  initContainers:
  - image: busybox
    name: init
    command:
    - sh
    - -c
    - exit 1
  containers:
  - image: busybox
    name: mymulticontainerpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
