apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pets.wisdompetmed.com
spec:
  group: wisdompetmed.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                breed:
                  type: string
                name:
                  type: string
  scope: Namespaced
  names:
    plural: pets
    singular: pet
    kind: Pet
    shortNames:
      - pt
