apiVersion: v1
kind: Service
metadata:
  name: mybluegreenservice
spec:
  selector:
    app: mywebapp
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
