apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: myjob
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: myjob
        command: ["sh", "-c", "echo 'CKAD' && sleep 10"]
        resources: {}
      restartPolicy: Never
  backoffLimit: 6
  completions: 2
  parallelism: 1
  ttlSecondsAfterFinished: 10
status: {}
